### ISSUE TITLE
require doesnt load the gem

### ISSUE THREAD

**Issue by tejasv02** [justeat/CalabashPageObjects#2]
I have installed the gem tried to require it 
`require 'calabash-page-objects`
which complains about gem unable to load 
Instead I need to use 
`require CalabashPageObjects`

**Comment by AndyBarnett** [comment]
Sorry it took so long for me to reply, but this has been fixed in PR #3, but I'm not allowed to mark this issue as closed, as I'm not longer the owner.
Perhaps @brainmurphy is able to do so?

**Comment by brainmurphy** [comment]
Close in #3
